### ISSUE TITLE
Error running the example.py

### ISSUE THREAD

**Issue by yorozcogonzalez** [rmcgibbo/pyvdwsurface#1]
Dear Robert
This code is exactly what I was looking for, thank you so much. But, after installing it and running your example I am getting the following error:
________________________________________________
-bash-4.2$ python example.py
Traceback (most recent call last):
  File "example.py", line 8, in <module>
    points = vdwsurface(atoms, elements=['C']*len(atoms), density=20)
  File "pyvdwsurface.pyx", line 50, in pyvdwsurface.vdwsurface
  File "stringsource", line 48, in vector.from_py.__pyx_convert_vector_from_py_std_3a__3a_string
  File "stringsource", line 15, in string.from_py.__pyx_convert_string_from_py_std__in_string
TypeError: expected bytes, str found
__________________________________________________
I am using python 3.6.2 and basically to install the code I am using: python install setup.py.
Do you have any idea what could be the problem?
Thank you in advance
Yoelvis

PS.
During the installation, I am getting some warnings, you can have a look here:
running install
running build
running build_ext
cythoning pyvdwsurface.pyx to pyvdwsurface.cpp
/users/PCS0202/bgs0361/bin/Python-3.6.2/lib/python3.6/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /users/PCS0202/bgs0361/vdw/pyvdwsurface-master/pyvdwsurface.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
building 'pyvdwsurface' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Iinclude/ -I/users/PCS0202/bgs0361/bin/Python-3.6.2/include/python3.6m -c pyvdwsurface.cpp -o build/temp.linux-x86_64-3.6/pyvdwsurface.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
pyvdwsurface.cpp: In function ‘PyObject* __pyx_pf_12pyvdwsurface_vdwsurface(PyObject*, __Pyx_memviewslice, PyObject*, double, double)’:
pyvdwsurface.cpp:2234:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (unlikely(!((__pyx_t_1 == __pyx_t_2) != 0))) {
                     ~~~~~~~~~~^~~~
pyvdwsurface.cpp:821:43: note: in definition of macro ‘unlikely’
   #define unlikely(x) __builtin_expect(!!(x), 0)
                                           ^
pyvdwsurface.cpp:2381:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (__pyx_t_4 = 0; __pyx_t_4 < __pyx_t_18; __pyx_t_4+=1) {
                       ~~~~~~~~~~^~~~~~~~~~~~
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Iinclude/ -I/users/PCS0202/bgs0361/bin/Python-3.6.2/include/python3.6m -c src/dotsphere.cc -o build/temp.linux-x86_64-3.6/src/dotsphere.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Iinclude/ -I/users/PCS0202/bgs0361/bin/Python-3.6.2/include/python3.6m -c src/vdwsurface.cc -o build/temp.linux-x86_64-3.6/src/vdwsurface.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
creating build/lib.linux-x86_64-3.6
g++ -pthread -shared build/temp.linux-x86_64-3.6/pyvdwsurface.o build/temp.linux-x86_64-3.6/src/dotsphere.o build/temp.linux-x86_64-3.6/src/vdwsurface.o -o build/lib.linux-x86_64-3.6/pyvdwsurface.cpython-36m-x86_64-linux-gnu.so
running install_lib
copying build/lib.linux-x86_64-3.6/pyvdwsurface.cpython-36m-x86_64-linux-gnu.so -> /users/PCS0202/bgs0361/bin/Python-3.6.2/lib/python3.6/site-packages
running install_egg_info
Writing /users/PCS0202/bgs0361/bin/Python-3.6.2/lib/python3.6/site-packages/pyvdwsurface-0.1-py3.6.egg-info

**Comment by yorozcogonzalez** [comment]
Solved just using python 2.7 and replace "ax = fig.add_subplot(111, projection='3d')" by "ax = Axes3D(fig)"
Thank you
