### ISSUE TITLE
Elements need to be encoded as bytes

### ISSUE THREAD

**Issue by Frank-Schiro** [rmcgibbo/pyvdwsurface#2]
I encountered an error with this:

```
elements = ['C', 'C', 'O', 'C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'F', 'F', 'F', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H']
pyvdwsurface.vdwsurface(coords_array, elements)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 17, in compute_ccs_v2
  File "pyvdwsurface.pyx", line 50, in pyvdwsurface.vdwsurface
  File "stringsource", line 48, in vector.from_py.__pyx_convert_vector_from_py_std_3a__3a_string
  File "stringsource", line 15, in string.from_py.__pyx_convert_string_from_py_std__in_string
TypeError: expected bytes, str found
```

My patch was to encode as bytes then it worked:
```elements = [atom.GetSymbol().encode('utf-8') for atom in molecule.GetAtoms()] ```

**Comment by rmcgibbo** [comment]
Sorry -- the last updates to this code are from over 9 years ago. I'm not maintaining it anymore.
